#!/bin/bash
$(echo "obase=bestchol; $(($(echo $WATER | tr -c -d '[:digit:]' | sed 's/^/-/;s/\(.\)/1*\1\+/g' | sed 's/.$//') + $(echo $STIR | tr -c -d '[:digit:]' | sed 's/^/-/;s/\(.\)/1*\1\+/g' | sed 's/.$//')))" | bc)
